-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: samples table — dual IDs + item_name / brand_name
-- Date: 2026-06-02
--
-- Changes:
--   1. Add  id SERIAL PRIMARY KEY  (auto-generated by DB — the "table id")
--   2. Keep sample_id INTEGER UNIQUE NOT NULL (supplied by the frontend)
--   3. Back-fill item_name and brand_name into existing item_description JSONB rows
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 1: Restructure sample_id + add new auto-generated id column
-- ─────────────────────────────────────────────────────────────────────────────

-- 1a. Remove the SERIAL default from sample_id (frontend will supply the value)
ALTER TABLE samples ALTER COLUMN sample_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS samples_sample_id_seq CASCADE;

-- 1b. Drop the existing PRIMARY KEY on sample_id
ALTER TABLE samples DROP CONSTRAINT IF EXISTS samples_pkey;

-- 1c. Add the new auto-generated id column as SERIAL PRIMARY KEY
ALTER TABLE samples ADD COLUMN IF NOT EXISTS id SERIAL;
ALTER TABLE samples ADD CONSTRAINT samples_pkey PRIMARY KEY (id);

-- 1d. Enforce sample_id as UNIQUE NOT NULL (frontend-provided business key)
ALTER TABLE samples ALTER COLUMN sample_id SET NOT NULL;
ALTER TABLE samples ADD CONSTRAINT samples_sample_id_unique UNIQUE (sample_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 2: Back-fill item_name and brand_name into existing JSONB rows
--         Idempotent — safe to run multiple times.
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE samples
SET item_description = (
    SELECT jsonb_agg(
        CASE
            WHEN (elem->>'item_name') IS NULL OR (elem->>'brand_name') IS NULL
            THEN elem
                || jsonb_build_object('item_name',  COALESCE(elem->>'item_name',  ''))
                || jsonb_build_object('brand_name', COALESCE(elem->>'brand_name', ''))
            ELSE elem
        END
    )
    FROM jsonb_array_elements(item_description) AS elem
),
updated_at = CURRENT_TIMESTAMP
WHERE item_description IS NOT NULL
  AND item_description != '[]'::jsonb;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 3: Verify — confirm both id and sample_id are returned for every row
-- ─────────────────────────────────────────────────────────────────────────────
SELECT
    s.id,
    s.sample_id,
    s.building_name,
    elem->>'sr_no'       AS sr_no,
    elem->>'item_name'   AS item_name,
    elem->>'brand_name'  AS brand_name,
    elem->>'description' AS description,
    elem->>'quantity'    AS quantity,
    elem->>'value'       AS value
FROM samples s,
     jsonb_array_elements(s.item_description) AS elem
ORDER BY s.id, (elem->>'sr_no')::int;

-- ─────────────────────────────────────────────────────────────────────────────
-- EXAMPLE INSERT — sample_id from frontend, id auto-generated by DB
-- ─────────────────────────────────────────────────────────────────────────────
/*
INSERT INTO samples
    (sample_id, project_id, building_name, site_name, location, work_done, item_description, add_fields)
VALUES
    (
        101,
        2,
        'Block A',
        'Main Site',
        '{"floor":"2nd","block":"B","wing":"East","coordinates":"19.0760,72.8777"}'::jsonb,
        'Flooring',
        '[
            {
                "sr_no": 1,
                "item_name": "Ceramic Tile",
                "brand_name": "Kajaria",
                "description": "60x60 Glossy White",
                "quantity": 100,
                "value": 45.50,
                "inventory_id": 12,
                "issued_qty": 100
            },
            {
                "sr_no": 2,
                "item_name": "Wall Putty",
                "brand_name": "Birla White",
                "description": "Interior Wall Putty 40kg",
                "quantity": 20,
                "value": 380.00
            }
        ]'::jsonb,
        '[]'::jsonb
    )
RETURNING id, sample_id, building_name, item_description;
-- Returns: id=1 (DB generated), sample_id=101 (from frontend)
*/
